### ISSUE TITLE
Update docs on how to import the library

### ISSUE THREAD

**Issue by lmas** [KennyShields/LoveFrames#163]
Hello, the docs at http://nikolairesokav.com/projects/loveframes/docs/information/gettingstarted needs to be updated to reflect the changes from issue #145 and the commit 4692f1e. 

Step 3 in the Installation section mentions: 
`require("path.to.loveframes")`
but it should be
`loveframes = require("path.to.loveframes")`

**Comment by KennyShields** [comment]
Fixed. Thanks for the report.
