### ISSUE TITLE
Suggestion: Context menus attachable to objects.

### ISSUE THREAD

**Issue by diath** [KennyShields/LoveFrames#165]
I couldn't really achieve this with the current implementation nor there's anything about it in the documentation so I assume the option does not exist. It would be nice if we could attach menu objects to specific objects, for example attaching menu to a columnlist would allow for adding menus that would operate on the list rows.

**Comment by Guard13007** [comment]
You can achieve this by checking what element the mouse is hovering over before creating the menu. I had to do this to achieve the opposite effect (checking that I *wasn't* hovering over something before creating the menu).

Look at the docs under util for getting what the mouse is hovering over, then a simple if statement to check whether you are over the desired object.

**Comment by diath** [comment]
Now that I think of it I could simply expand the functionality from mousepressed event in the desired object. Although I guess a generic way of hooking menus to objects would be nice.
