### ISSUE TITLE
Update .md?

### ISSUE THREAD

**Issue by tvvocold** [KennyShields/LoveFrames#167]
Looks like the [doc](http://nikolairesokav.com/projects/loveframes/docs) and [demo]( http://nikolairesokav.com/projects/loveframes/) r down.
BTW, so do lightpaste.com.(i got 403 error)

**Comment by Guard13007** [comment]
For now just look at the [wiki](https://github.com/KennyShields/LoveFrames/wiki) here for docs. Dunno about the demo. I asked about it on the release thread on the LOVE forums, but no reply.

**Comment by KennyShields** [comment]
Just updated the readme. As for the demo, you can download the source at https://github.com/KennyShields/LoveFrames-demo.
