### ISSUE TITLE
How can I get the data of a columnlist?

### ISSUE THREAD

**Issue by JetGH** [KennyShields/LoveFrames#168]
I'm trying to get the data of the rows of a column list when someone triggers an OnClick event (of a button). I know I can obtain row data with OnRowClicked and OnRowRightClicked events but I must get it on a button click as it is part of a form and the button is submitting it. Surely there is a way to do this? It would seem odd for there not to be one.

Any ideas?

**Comment by KennyShields** [comment]
You can get all of the rows in a columnlist by accessing the objects internals directly:

```lua
local rows = columnlist.internals[1].children
```

**Comment by JetGH** [comment]
Thanks! I assumed there would be an explicit method to obtain the data but this works just fine too!

**Comment by KennyShields** [comment]
No problem!
