### ISSUE TITLE
Unable to find function NewObject.

### ISSUE THREAD

**Issue by Lundex** [KennyShields/LoveFrames#169]
attempt to call field 'NewObject' (a nil value) is the error I get.

I looked through the library, and the function for NewObject is nowhere to be found.

**Comment by KennyShields** [comment]
The NewObject function is in init.lua: https://github.com/KennyShields/LoveFrames/blob/5abc8a4a65478ce995976c362a3bb60218ae8c71/init.lua#L388. Can you post a screenshot of the exact error you are getting?

**Comment by Lundex** [comment]
http://puu.sh/hhJCi/da871723b8.png

**Comment by Lundex** [comment]
Nevermind I figured out the issue. I used require("lib/loveframes") when it should be require("lib.loveframes")
