### ISSUE TITLE
Typo on wiki, Textinput object, "DeselctAll"

### ISSUE THREAD

**Issue by Guard13007** [KennyShields/LoveFrames#172]
I would've edited it myself if I could, but I can't seem to figure out how to do this.

[The Textinput object](https://github.com/KennyShields/LoveFrames/wiki/The-Textinput-Object) wiki page:

"DeselctAll - De-selects all of the object's text"

Should be "DeselectAll"

**Comment by KennyShields** [comment]
Fixed. Thanks for the report.
