### ISSUE TITLE
"demo" object in wiki

### ISSUE THREAD

**Issue by qubodup** [KennyShields/LoveFrames#174]
Hi,

Some wiki page samples refer to a variable called `demo`, like for example
https://github.com/KennyShields/LoveFrames/wiki/The-Button-Object

uses `demo.centerarea`

What is `demo` and how to create it to get the samples to run?

**Comment by KennyShields** [comment]
The demo variable is from the Love Frames demo: https://github.com/KennyShields/LoveFrames-demo. A lot of the code in the wiki was taken from the examples in the demo. I'd suggest removing references to the demo variable to get the code to work.
